{
  "name": "EVIL FOREST",
  "introAtmosphere": "Legends spoke of hidden gold buried deep within the forests of the old Benin Kingdom.🌳🪾 Greedy adventurers entered the forest searching for riches before sunrise. By nightfall, the paths behind them had vanished into the fog.🌫️ Strange drums echoed between the trees as shadows moved in silence.🧌 The forest was never protecting treasure. It was feeding on those who searched for it.",
  "openingNarrative": [
    "You followed the old map 🗾 deeper into the forest, even after the villagers begged you to turn back.",
    "You came to the Benin forest searching for gold, but the silence between the trees felt wrong.",
    "Your lantern flickered as the last path behind you disappeared into the fog.🌫️",
    "You were promised riches hidden beneath the ancient forest ruins.🪾 Nobody mentioned the screams at night.",
    "You stepped over broken warning signs as distant drums echoed somewhere ahead.",
    "You thought the stories about the Evil Forest were meant to scare tourists away. You were wrong.",
    "You entered the forest with a backpack, a rusted machete, and a map stained with dried blood.",
    "You heard something moving beside you the moment the sun disappeared behind the trees 🌅👣.",
    "You joined the expedition for treasure, but now survival is the only thing that matters.",
    "You reached the ancient forest gates at midnight, just as the drums suddenly stopped."
  ],
  "midNarrative": [
    "I really thought this treasure💰 was going to change my life forever.",
    "The deeper we go, the more this forest feels wrong.🌲😨",
    "At this point, I cannot even remember the way back anymore.",
    "Nobody in the group says it out loud, but we are all terrified now.",
    "I should have listened when they warned us about this place.",
    "The gold stopped feeling important the moment the screaming started.",
    "Every step 👣 deeper into this forest feels like a mistake.",
    "I came here chasing riches… now I just want to survive the night.",
    "Something inside these woods does not want us leaving alive.",
    "The silence in this forest feels heavier than the darkness itself.",
    "At first it felt like an adventure. Now it feels like a death sentence.⚰️",
    "I cannot tell if we are searching for the treasure… or if something is leading us somewhere.",
    "Nobody has smiled since we entered this forest.",
    "I have a feeling the treasure was only bait to bring people here.",
    "The strange thing is… the deeper we go, the harder it becomes to stop walking.",
    "I thought fear would make us turn back. Instead, it keeps pushing us forward.",
    "Every ruined statue we pass feels like a warning we ignored.",
    "The forest feels alive tonight… and it knows we are here.",
    "I do not think anyone who entered this place ever truly escaped it.",
    "Part of me still wants the treasure. That is the scariest part."
  ],
  "worldEvents": [
    "Distant ancestral drums call for fresh blood.",
    "The iroko trees shook violently as if possessed.",
    "Thick white fog swallowed the path in seconds.",
    "Something massive moved behind the sacred trees.",
    "A lone lantern burned with unnatural green flame.",
    "The entire forest fell into deadly silence.",
    "The drums stopped — then beat from inside the trees.",
    "The earth trembled like an angry ancestor.",
    "A procession of headless warriors marched through the mist.",
    "A woman’s voice sang a forgotten coronation song backwards.",
    "Invisible children ran past, giggling in old Edo.",
    "Burning eyes opened on the bark of ancient trees.",
    "A giant shadow with bronze chains dragged across the path.",
    "All the fetish masks slowly turned to face the group.",
    "A circle of glowing ancestral skulls rose from the mud.",
    "Whispers called each survivor by their mother’s secret name."
  ],
  "survival": [
    "A deadly snake 🐍 dropped from a branch, but {Player} killed it 🪈🐍 just before it struck another survivor.",
    "After hours of searching, a hidden stream 🌊🌊 was discovered and {Player} rushed to drink from it first.",
    "A loud scream echoed through the forest after a soldier ant 🐜 bit {Player} on the neck.",
    "The muddy ground suddenly collapsed beneath {Player}, forcing another survivor to pull them out.",
    "{Player} almost fainted after touching what they thought was a tree root. It moved.",
    "Something moved behind the trees and {Player} immediately ran in the wrong direction.",
    "A strange whisper circled the camp all night, keeping {Player} awake until sunrise.",
    "{Player} ran from a shadow in the fog only to crash straight into a tree.",
    "{Player} found ancient coins scattered near a ruined shrine.",
    "While searching the ruins, {Player} accidentally stepped into a nest of angry insects.",
    "The silence became unbearable, so {Player} started singing loudly to calm the tension.",
    "An old machete covered in rust was discovered buried near the path by {Player}.",
    "A hidden trap nearly caught {Player}, but another survivor reacted just in time.",
    "The deeper the group traveled, the more nervous {Player} became.",
    "While everyone argued about the map, {Player} quietly stole extra food for later.",
    "The cold night air became unbearable, so {Player} slept beside the dying fire alone.",
    "Strange markings carved into the trees were noticed first by {Player}.",
    "The group froze in silence after hearing {Player} whisper, “Something is following us.”",
    "{Player} heard whispers calling their name deep inside the forest.",
    "{Player} used a burning branch to scare away something hiding in the dark.",
    "{Player} found a abandoned shrine and immediately started apologizing to everything.",
    "{Player} refused to believe in curses until their hair started moving on its own.",
    "{Player} spent their last moments wondering if this counts as a “rich experience.”"
  ],
  "elimination": [
    "{Victim} disappeared into the fog after following distant drum sounds alone.",
    "A hidden trap snapped beneath {Victim}, dragging them deep underground.",
    "{Killer} shoved {Victim} toward the moving shadows and kept running.",
    "While searching for gold, {Victim} disturbed something sleeping beneath the ruins.",
    "The camp went silent after {Victim} wandered too far from the fire.",
    "{Victim} drank water from a shrine pool. Their eyes went white before they fell.",
    "{Killer} whispered something in Hausa. {Victim} walked straight into the forest and never came back.",
    "{Victim} refused to pour libation at the old oak. The forest took payment anyway.",
    "A masquerade emerged from nowhere. {Victim} couldn’t look away. They walked toward it smiling.",
    "{Killer} tied {Victim} to a tree marked with red chalk and left them screaming.",
    "{Victim} heard their own voice calling from deeper in the forest. They went to find it.",
    "{Victim} stepped on a line of white powder someone had drawn across the path. Everything after that was wrong.",
    "{Killer} paid the forest something. {Victim} became the price.",
    "{Victim} found a fresh grave with their own name carved on it. They sat down and waited.",
    "{Victim} ate mango blessed by the wrong hands. Poison wasn’t quick.",
    "A beautiful woman in white appeared on the path. {Victim} followed her into the mist.",
    "{Victim} laughed and said “worst case scenario, I die in the forest.” The forest took notes.",
    "{Killer} gave {Victim} a choice. Both options led downward.",
    "{Killer} offered {Victim} a “small drink” from a calabash. Everything after tasted like regret.",
    "The ancestors wanted something. {Victim} offered apologies. Apologies don’t feed the dead.",
    "{Victim}’s last words were “at least I tried.” The forest admired the effort. Then took payment.",
    "The forest floor opened beneath {Victim} mid-step. {Killer} watched them sink into earth that was still breathing.",
    "{Victim} touched an ancient stone covered in symbols. Their hand fused to it. {Killer} kept walking.",
    "A flock of birds erupted from nowhere, moving in formation toward {Victim}’s face. When the wings cleared, {Victim} was gone.",
    "The vines moved like they had intention. They wrapped around {Victim} slowly, then all at once.",
    "The ground beneath {Victim} turned to water without warning.",
    "{Victim} was dragged into the undergrowth by pale hands.",
    "{Victim} hanged from a tree by invisible ropes.",
    "{Killer} offered {Victim} as sacrifice on the blood altar.",
    "Black vines strangled {Victim} in silence.",
    "{Killer} whispered directions that {Victim} followed into deeper darkness. No one found them walking out.",
    "An old woman offered {Victim} shelter in her hut. Morning never came to that hut.",
    "{Victim}’s reflection in the ritual mirror stepped out and took their place.",
    "{Killer} swapped {Victim}’s protective charm for a cursed stone, inviting the darkness.",
    "The red clay of the earth rose up to fill {Victim}’s lungs until they hardened into a statue."
  ],
  "winner": [
    "Morning finally reached the forest.",
    "Covered in dirt, blood, and ash, {Winner} walked out alone.",
    "The treasure bag felt heavier than before.",
    "The drums suddenly stopped as {Winner} crossed the forest border.",
    "For the first time all night, the trees stood completely still.",
    "But the whispers never truly faded.",
    "The villagers froze when they saw {Winner} return at sunrise.",
    "Nobody asked where the others were.",
    "The fear in {Winner}’s eyes already answered everything.",
    "Gold coins spilled from {Winner}’s bag onto the muddy road.",
    "Yet somehow, surviving the forest felt more valuable than the treasure itself.",
    "The fog slowly cleared behind {Winner} as dawn approached.",
    "Somewhere deep inside the forest, distant drums began again.",
    "Another group would eventually come searching for gold.",
    "Every step away from the forest felt unreal to {Winner}.",
    "The silence outside almost sounded wrong after surviving the night inside.",
    "The forest gates stood open behind {Winner}.",
    "As if the Evil Forest was patiently waiting for them to return someday.",
    "The treasure was real after all.",
    "But judging by the shaking hands of {Winner}, the price was far too high.",
    "At sunrise, {Winner} finally understood the truth.",
    "The forest never protected the treasure. It was feeding on greed all along.",
    "The rain stopped the moment {Winner} escaped the forest.",
    "Far behind the trees, something screamed in frustration before fading into silence.",
    "As dawn finally broke through the trees, {Winner} walked out of the Evil Forest alone.",
    "The drums stopped the moment {Winner} escaped the cursed forest alive.",
    "Covered in mud and blood, {Winner} survived what nobody else could.",
    "The forest grew silent as {Winner} disappeared into the morning fog.",
    "{Winner} left the forest with the treasure… and memories better forgotten.",
    "Even after escaping, {Winner} could still hear whispers from the trees behind them.",
    "The gates of the forest closed slowly behind {Winner} at sunrise.",
    "Nobody believed the story {Winner} told after returning from the forest.",
    "As the rain finally stopped, {Winner} looked back at the forest one last time.",
    "The Evil Forest spared {Winner} tonight… but it never truly lets anyone leave."
  ]
}
